#
###################################
# Site wide configuration
####################################
#
title: TWO2TWO2TWO2TWO2
email: two2er2@gmail.com
description: I love markdown and knowledge written in markdown.
url: https://two2er.github.io
keywords: ["CS"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Shanghai
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /articles/:year-:month/:title
  pages:
    output: true
    permalink: /pages/:path

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: two2er
  avatar: avatar.jfif
  job: 二
  bio: reinventing the wheel
  email: two2er@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: two2er
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
