future: true
permalink: /:title/
url: http://two2er.github.io
name: ZYF
author: zheng yangfeng
qq: 1285580823
email: dtcf@163.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: yourID
about: "这里是 Your 的个人博客，创建于 20xx 年。"

safe: true
paginate: 20
